//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KaoshiDBEntities : DbContext
    {
        public KaoshiDBEntities()
            : base("name=KaoshiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<y_SysPerssions> y_SysPerssions { get; set; }
        public DbSet<y_UserPession> y_UserPession { get; set; }
        public DbSet<y_Users> y_Users { get; set; }
    }
}
